# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

# name: Ruby

# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main, develop ]

# jobs:
#   test:

#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         ruby-version: ['2.6', '2.7', '3.0']

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Ruby
#     # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
#     # change this to (see https://github.com/ruby/setup-ruby#versioning):
#     # uses: ruby/setup-ruby@v1
#       uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
#       with:
#         ruby-version: ${{ matrix.ruby-version }}
#         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
#     - name: Install dependencies
#       run: bundle install
#     - name: Run tests
#       run: rspec spec

name: Tests

on: pull_request

jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Setup RSpec
        run: |
          [ -f Gemfile ] && gem install bundler:2.2.5
          gem install --no-document rspec:'~>3.0'
      - name: RSpec Report
        run: rspec --force-color --format documentation